#README
#Line 27 replace email_address with email address
#Line 30 replace password with password
#Change "message to send" in line 105 to the message to send N.B: go to next line of message with \n 
 
import time
 
from selenium import webdriver
from selenium.common.exceptions import UnexpectedAlertPresentException
from selenium.webdriver.common.keys import Keys
import pandas as pd
 
# driver = webdriver.Firefox(executable_path='<Path>/geckodriver.exe')
# This block of code is used to block the notification popup which is generated by site
options = webdriver.ChromeOptions()
options.add_argument("--disable-notifications")
 
# to open chrome webbrowser and maximize the window
driver = webdriver.Chrome(executable_path="chromedriver.exe", chrome_options=options)
driver.maximize_window()
 
#Implicit Wait when element is taking time to load
driver.implicitly_wait(20)
 
# connect to the specific ip address
driver.get("http://www.facebook.com")

 
# Waiting time 
time.sleep(5)
driver.get('https://www.facebook.com/search/posts/?q=%22'+'Appzone Developer'+'%22&epa=SERP_TAB')

        
DF = pd.DataFrame({'Related Posts': LINKS,
                   'Likes Count':LIKES,
                   'Comments Count': COMMENTS,
                   'Shares Count': SHARES,
                   'Date Published': DATE,
                   })  #defines columns for storing the Names and H-index using pandas.
DF.to_csv('facebook3.csv') #specifies the name of the csv file"""
